### PR TITLE
bumps chalk

### PR DESCRIPTION
**Pull request by mdreizin**
I have bumped `chalk` to the latest version.

Also it would be nice to update `eazy-logger` to use updated version of `tfunk`.

### CODE REVIEW

**Comment by mdreizin** [comment]
@shakyShane Have you had a chance to look it?

**Comment by shakyShane** [comment]
Thanks! 

I'll update easy logger too :)

**Comment by mdreizin** [comment]
@shakyShane Thanks! Looking forward to try it ;)

**Comment by shakyShane** [comment]
published

**Pull request merged**
